KlinicosDirectivos/ViewModels/Semanal.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace KlinicosDirectivos.ViewModels
{
    public class Semanal
    {
        public int cantidadAtenciones { get; set; }
        public int  cantidadEvoluciones { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public int idProfesional { get; set; }

        public string NomyAp()
        {
            return this.Nombre + " " + this.Apellido;
        }
    }
}

KlinicosDirectivos/Controllers/ProfesionalController.cs
using KlinicosDirectivos.ViewModels;
using Rotativa;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KlinicosDirectivos.Controllers
{
    public class ProfesionalController : Controller
    {
        // GET: Profesional
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult DetalleProfesional(int idProfesional)
        {
            DateTime  hasta = DateTime.Now;
            DateTime desde = DateTime.Now.AddDays(-7);

            Klinicos_BEntities entidades = Repositorio.CrearEntityFramework();
            Profesionales profesional = entidades.Profesionales.Where(x => x.id == idProfesional && x.vigente == true).FirstOrDefault();
            /*List<Especialidades> especialidades = entidades.Especialidades
                .Join(entidades.ProfesionalesEspecialidades, e => e.id, pe => pe.idEspecialidad, (e, pe) => new { especialidad = e, profesional = pe.idProfesional })
                .Where(x => x.profesional == idProfesional)
                .Select(x => x.especialidad).ToList();*/

            var especialidades = entidades.SP_ESPECIALIDADES_X_PROFESIONAL((int?)idProfesional).ToList();
            

            Usuarios usuario = entidades.Usuarios.Where(x => x.idProfesional == idProfesional).FirstOrDefault();
            //var turnosIngresados = entidades.Turno.Join(entidades.Atenciones, t => t.Id, a => a.idTurno, (t, a) => new { atencion = a, idprofe = t.AtendidoPorRefId }).Where(x => x.idprofe == idProfesional).Count();
            //  var ultimoTurno = turnosReservados.OrderByDescending(x => x.Turno.FechaYHora).Select(x => x.Turno).FirstOrDefault();
            //var Ultimasatenciones = entidades.AtencionesEstados.Where(x => x.idProfesionalDestino == idProfesional).OrderByDescending(x => x.llamadosUltimaFechayHora).FirstOrDefault();


            var turnosReservados = entidades.TurnosReserva.Where(x => x.Turno.AtendidoPorRefId == idProfesional && (x.Turno.FechaYHora > desde && x.Turno.FechaYHora < hasta  )).Count(); //Reservas de hoy en adelante
            var turnosHistoricos = entidades.Turno_Historicos.Where(x => x.AtendidoPorRefId == idProfesional && (x.FechaYHora > desde && x.FechaYHora < hasta)).Count(); // Reservas en el historico
            int cantidadTurnosReservados = turnosReservados + turnosHistoricos; // Usar esta variable en la vista

            var cantidadturnosEspontaneos = entidades.AtencionesEstados.Where(x => x.idProfesionalDestino == idProfesional && (x.Atenciones.idTurno.Equals(null) || x.Atenciones.idTurno == 0) && ( x.fechaCrea > desde && x.fechaCrea < hasta )).Count();

            var ingresosXProfesional = entidades.AtencionesEstados.Where(x => x.idProfesionalDestino == idProfesional && (x.fechaCrea > desde && x.fechaCrea< hasta));

            var evolucionesXProfesional = entidades.Evoluciones.Where(x => x.idProfesional == idProfesional && (x.fechaCrea> desde && x.fechaCrea< hasta));

            VMProfesionalDesempeño viewModel = new VMProfesionalDesempeño(usuario , profesional , especialidades);
            viewModel.cantidadTurnosEspontaneos = cantidadturnosEspontaneos;
            viewModel.cantidadTurnosReservados = cantidadTurnosReservados;
            viewModel.totalAtendidos = evolucionesXProfesional.Count();
            viewModel.totalIngresos = ingresosXProfesional.Count();

            viewModel.ObtenerDiasAtencion(evolucionesXProfesional.ToList());
            return View(viewModel);
        }

        private bool EntreFechas(DateTime fechaYHora, DateTime desde, DateTime hasta)
        {
            return fechaYHora > desde && fechaYHora < hasta;
        }


        private List<SemanalProfesional> CastearASemanales(IEnumerable<AtencionesEstados> listaAtenciones, IEnumerable<Evoluciones> listaEvoluciones)
        {
            return new List<SemanalProfesional>();
        }

        public int MyProperty { get; set; }






        public ActionResult Default(DetalleSemanalPartialVM model)
        {
            int idEstablecimiento = 3;
            Reportes reporte = null;
            ReportesEspecialidades reporteEspecialidad = null;
            DataSet dataset;
            Klinicos_BEntities modelo = new Klinicos_BEntities();
            reporteEspecialidad = modelo.ReportesEspecialidades.Where(x => x.idEspecialidad == model.idEspecialidad).FirstOrDefault();
            string sp = reporteEspecialidad == null ? "[Atencion].[RegistroDiarioGeneral_entrefechas_multisets]" : reporteEspecialidad.storeProcedure;

            dataset = getRegistroDiarioDataSet(
                    sp,
                    model.fechadesde,
                    model.fechaHasta,
                    model.mes,
                    model.anio,
                    model.mesHasta,
                    model.anioHasta,
                    model.idSector,
                    model.idEspecialidad,
                    model.idProfesional,
                    model.tipoEspecialidad,
                    idEstablecimiento
                );

            if (dataset == null)
            {
                //Error("No Existen datos que informar");
                return View(model);
            }
            else
            {


                DataTable dtHeader1 = dataset.Tables[0];
                int leftMargin = 10;
                int bottomMargin = 10;
                int rightMargin = 10;
                int topMargin = 10;
                int.TryParse(reporte.pageMarginsLeft, out leftMargin);
                int.TryParse(reporte.pageMarginsBottom, out bottomMargin);
                int.TryParse(reporte.pageMarginsRight, out rightMargin);
                int.TryParse(reporte.pageMarginsTop, out topMargin);

                return new ViewAsPdf(reporteEspecialidad == null ? reporte.defaultHtml : reporteEspecialidad.html, dataset)
                {
                    FileName = reporte.nombre.Replace(" ", "_") + DateTime.Now.ToShortDateString().Replace("/", "_") + ".pdf",
                    PageOrientation = reporte.pageOrientation == "Landscape" ? Rotativa.Options.Orientation.Landscape : Rotativa.Options.Orientation.Portrait,
                    PageSize = reporte.pageSize == "A4" ? Rotativa.Options.Size.A4 : Rotativa.Options.Size.Legal,
                    PageMargins = { Left = leftMargin, Bottom = bottomMargin, Right = rightMargin, Top = topMargin },
                    CustomSwitches = "--footer-left \"Generado el : " + DateTime.Now.Date.ToString("MM/dd/yyyy") + "  Página: [page]/[toPage]\"" + " --footer-font-size \"10\" --footer-spacing 2 --footer-font-name \"calibri light\""
                };

                //else if (model.formato == "EXCEL")
                //{
                //    Response.AddHeader("content-disposition", "attachment;filename=" + reporte.nombre.Replace(" ", "_") + '_' + DateTime.Now.ToShortDateString().Replace("/", "_") + ".xls");
                //    Response.AddHeader("Content-Type", "application/vnd.ms-excel");
                //    return View("~/Views/Reporte/reporte_excel_multiResultSets.cshtml", dataset);
                //}
            }
        }








        public DataSet getRegistroDiarioDataSet(string storeProcedure, DateTime? fecha, DateTime? fechaHasta, string mes, string anio, string mesHasta, string anioHasta, int? idSector, int? idEspecialidad, int? idProfesional, string tipoEspecialidad, int idEstablecimiento)
        {

            SqlConnection con = new SqlConnection(@"data source = 127.0.0.1; initial catalog = KLINICOS; persist security info = True; user id = sa; password = sql2018 *; MultipleActiveResultSets = True; App = EntityFramework");
            DataSet dst = new DataSet();
            SqlCommand cmd = new SqlCommand(storeProcedure, con);
            cmd.Parameters.Add("@fecha", SqlDbType.DateTime).Value = fecha == null ? SqlDateTime.Null : (DateTime)fecha;
            cmd.Parameters.Add("@fechahasta", SqlDbType.DateTime).Value = fechaHasta == null ? SqlDateTime.Null : (DateTime)fechaHasta;
            cmd.Parameters.Add("@mes", SqlDbType.VarChar).Value = string.IsNullOrEmpty(mes) ? SqlString.Null : mes;
            cmd.Parameters.Add("@anio", SqlDbType.VarChar).Value = string.IsNullOrEmpty(anio) ? SqlString.Null : anio;
            cmd.Parameters.Add("@mesHasta", SqlDbType.VarChar).Value = string.IsNullOrEmpty(mesHasta) ? SqlString.Null : mesHasta;
            cmd.Parameters.Add("@anioHasta", SqlDbType.VarChar).Value = string.IsNullOrEmpty(anioHasta) ? SqlString.Null : anioHasta;
            cmd.Parameters.Add("@idEstablecimiento", SqlDbType.Int).Value = idEstablecimiento;
            cmd.Parameters.Add("@idSector", SqlDbType.Int).Value = idSector == null ? SqlInt32.Null : (int)idSector;
            cmd.Parameters.Add("@idEspecialidad", SqlDbType.Int).Value = idEspecialidad == null ? SqlInt32.Null : (int)idEspecialidad;
            cmd.Parameters.Add("@idProfesional", SqlDbType.Int).Value = idProfesional == null ? SqlInt32.Null : (int)idProfesional;
            cmd.Parameters.Add("@tipoEspecialidad", SqlDbType.VarChar).Value = string.IsNullOrEmpty(tipoEspecialidad) ? SqlString.Null : tipoEspecialidad;
            cmd.CommandType = CommandType.StoredProcedure;
            SqlDataAdapter da = new SqlDataAdapter();
            da.SelectCommand = cmd;
            da.Fill(dst);
            return dst;
        }


        


    }


}

KlinicosDirectivos/Controllers/SemanalController.cs
using KlinicosDirectivos.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KlinicosDirectivos.Controllers
{
    public class SemanalController : Controller
    {
        // GET: Semanal
        public ActionResult Index()
        {

            Klinicos_BEntities entidades = Repositorio.CrearEntityFramework();
            List<Sectores> listaSectores = entidades.Sectores.ToList();
            List<SelectListItem> sectores = new List<SelectListItem>();
            foreach (var sector in listaSectores)
            {
                sectores.Add(new SelectListItem() { Text = sector.nombre, Value = sector.id.ToString() });
            }




            var establecimientosTotales = entidades.Establecimientos.ToList();
            Establecimientos nombreEsta = new Establecimientos();
            string lugar = string.Empty;
            int id = (int)Session["Establecimiento"];
            foreach (var item in establecimientosTotales)
            {
                if (item.id == id)
                {
                    nombreEsta = item;
                    lugar = nombreEsta.nombre;
                }
            }

            ViewBag.Sectores = sectores;
            ViewBag.Establecimiento = lugar;

            List<ProfesionalVM> listProfesionalesVM = new List<ProfesionalVM>();
            IEnumerable<Profesionales> listProfesionales = entidades.ProfesionalesDisponibles.Join(entidades.Profesionales, pd => pd.id, p => p.id, (pd, p) => p);
            //var EspecialidadesXProfesional = entidades.ProfesionalesEspecialidades.Join(entidades.Especialidades, pe => pe.idEspecialidad, e => e.id, (pe, e) => new { idProfesional = pe.idProfesional, especialidad = e });
            var EspecialidadesXProfesional = new List<Especialidades>();
            foreach (Profesionales profesional in listProfesionales)
            {
                int? idprof = profesional.id;
                var  listaresultado = entidades.SP_ESPECIALIDADES_X_PROFESIONAL(idprof).ToList();
                List<Especialidades> listaEspecialidades = listaresultado;
                ProfesionalVM profesionalVM = new ProfesionalVM(profesional, listaEspecialidades);
                listProfesionalesVM.Add(profesionalVM);
            }

            return View("Inicio", listProfesionalesVM);
        }


        public ActionResult IndexFiltrado(int idSector)
        {
            try
            {



                Klinicos_BEntities entidades = Repositorio.CrearEntityFramework();

                List<ProfesionalVM> listProfesionalesVM = new List<ProfesionalVM>();
                IEnumerable<Profesionales> listProfesionales = entidades.ProfesionalesDisponibles.Join(entidades.Profesionales, pd => pd.id, p => p.id, (pd, p) => p);
                //var EspecialidadesXProfesional = entidades.ProfesionalesEspecialidades.Join(entidades.Especialidades, pe => pe.idEspecialidad, e => e.id, (pe, e) => new { idProfesional = pe.idProfesional, especialidad = e });

                var listProfEnSector = entidades.UsuariosSectores.Where(x => x.Sectores.id == idSector).Select(x => x.Usuarios.idProfesional).ToList();

                foreach (Profesionales profesional in listProfesionales)
                {
                    if (listProfEnSector.Contains(profesional.id))
                    {
                        //List<Especialidades> listaEspecialidades = EspecialidadesXProfesional.Where(x => x.idProfesional == profesional.id).Select(exp => (Especialidades)exp.especialidad).ToList();
                        List<Especialidades> listaEspecialidades = entidades.SP_ESPECIALIDADES_X_PROFESIONAL(profesional.id).ToList();
                        ProfesionalVM profesionalVM = new ProfesionalVM(profesional, listaEspecialidades);
                        listProfesionalesVM.Add(profesionalVM);
                    }
                }

                return PartialView("_TablaProfesionales", listProfesionalesVM);

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                throw ex;
            }
        }



        public ActionResult SemanalSector(int idSector)
        {
            DateTime fechaDesde = DateTime.Now.AddDays(-7);
            DateTime fechaHasta = DateTime.Now;
            Klinicos_BEntities entities = Repositorio.CrearEntityFramework();
            //var AtencionesXProfesional = from profesional in entities.Profesionales
            //                             join ae in entities.AtencionesEstados
            //                             on new { profe = (int?)profesional.id , estable = Boolean.TrueString } equals new { profe = ae.idProfesionalDestino  , estable = ae.Evoluciones.Select(x => x.idSector).Contains(1).ToString() }
            //                             into pGroup
            //                             where pGroup.Count() > 10 
            //                             select new Semanal
            //                             {
            //                                 idProfesional = profesional.id,
            //                                 Apellido = profesional.primerApellido,
            //                                 Nombre =  profesional.primerNombre,
            //                                 cantidadAtenciones = pGroup.Count()

            //                             };

            //foreach (Semanal semanal in AtencionesXProfesional)
            //{
            //    Console.WriteLine("El profesional {0} tiene {1} Atenciones", semanal.NomyAp(), semanal.cantidadAtenciones);
            //    semanal.cantidadEvoluciones = ObtenerEvolucionesPorProfesionales(semanal.idProfesional, fechaDesde, fechaHasta, entities);
            //}
            int idEstableciemiento = (int)Session["Establecimiento"];
            var atencionesXProfesional = entities.SP_OBTENER_SEMANAL_ATENCIONES("12", "2019", idSector, idEstableciemiento);
            var evolucionesXProfesional = entities.SP_OBTENER_SEMANAL_EVOLUCIONES("12", "2019", idSector, idEstableciemiento);
            List<Semanal> semanales = CastearASemanales(atencionesXProfesional.ToList(), evolucionesXProfesional.ToList());

            return View("Semanal", semanales.Take(10));
        }

        private List<Semanal> CastearASemanales(List<SP_OBTENER_SEMANAL_ATENCIONES_Result> listaAtenciones, List<SP_OBTENER_SEMANAL_EVOLUCIONES_Result> listaEvoluciones)
        {
            List<Semanal> listaSemanal = new List<Semanal>();
            foreach (var atencion in listaAtenciones)
            {
                Semanal semanal = new Semanal();
                semanal.Apellido = atencion.primerApellido;
                semanal.Nombre = atencion.primerNombre;
                semanal.idProfesional = (int)atencion.idprof;
                semanal.cantidadAtenciones = (int)atencion.cantAtenciones;
                semanal.cantidadEvoluciones = 0;
                if (listaEvoluciones.Exists(x => x.idProfesional == semanal.idProfesional))
                {
                    var evolucion = listaEvoluciones.FirstOrDefault(x => x.idProfesional == semanal.idProfesional);
                    semanal.cantidadEvoluciones = (int)evolucion.cantidad;

                }
                listaSemanal.Add(semanal);
            }
            return listaSemanal;
                
        }

        private int ObtenerEvolucionesPorProfesionales(int idProfesional, DateTime fechaDesde, DateTime fechaHasta, Klinicos_BEntities entities)
        {
            int cantidad;
            cantidad = entities.Evoluciones.Where(x => x.idProfesional == idProfesional).Count();
            return cantidad;
        }




    }
}

KlinicosDirectivos/Views/Semanal/Inicio.cshtml
@model  IEnumerable<KlinicosDirectivos.ViewModels.ProfesionalVM>
@{
    ViewBag.Title = "Inicio";
}


<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" ; style="height:40%">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>


    @Styles.Render("~/Content/plugins/DataTables")


</head>

<style>
    .botonNuevo {
        padding: 15px;
        background: #00b7f8;
        border-bottom: 5px solid #0045a6;
        border-radius: 12px;
        color: #fff;
        cursor: pointer;
        font-family: 'Raleway', Arial, Helvetica;
        font-size: 20px;
        text-align: center;
        transition: all 0.2s ease 0s;
    }

        .botonNuevo:hover {
            box-shadow: 2px 2px 2px #777, 0px 0px 35px 0px #00b7f8;
            border-bottom: 1px solid #0045A6;
            text-shadow: 0px 0px 5px #fff, 0px 0px 5px #fff;
            color: cornflowerblue;
        }

    .lista {
        border-radius: 69px 69px 69px 69px;
        -moz-border-radius: 69px 69px 69px 69px;
        -webkit-border-radius: 69px 69px 69px 69px;
        padding: 15px;
        border: 2px solid white;
        border-color: white;
        font-size: 20px;
        text-align: center;
        background-color: black;
        color: white;
    }


    .boton2 {
        background-color: black;
        border-bottom-color: white;
        border-radius: 6px;
        border-style: double;
    }

        .boton2:hover {
            background-color: darkgrey;
            color: wheat;
            border-bottom-style: double;
            border-style: inset;
        }

    .boton-lista {
        background-color: black;
        color: white;
    }

    .boton {
        background: #00b7f8;
        border-bottom: 5px solid #0045a6;
        border-radius: 12px;
        color: #fff;
        cursor: pointer;
        display: block;
        font-family: 'Raleway', Arial, Helvetica;
        font-size: 20px;
        text-align: center;
        transition: all 0.2s ease 0s;
        width: 120px;
    }

        .boton:hover {
            background: #0096f7;
        }

        .boton:active {
            box-shadow: 2px 2px 2px #777, 0px 0px 35px 0px #00b7f8;
            border-bottom: 1px solid #0045A6;
            text-shadow: 0px 0px 5px #fff, 0px 0px 5px #fff;
        }


    .search_categories {
        padding: 15px;
        background: #00b7f8;
        border-bottom: 5px solid #0045a6;
        border-radius: 12px;
        color: #fff;
        cursor: pointer;
        display: block;
        font-family: 'Raleway', Arial, Helvetica;
        font-size: 20px;
        text-align: center;
        transition: all 0.2s ease 0s;
        width: 250px;
    }

        .search_categories .select {
            width: 120%;
            background: url('arrow.png') no-repeat;
            background-position: 80% center;
        }

            .search_categories .select select {
                background: transparent;
                line-height: 1;
                border: 0;
                padding: 0;
                border-radius: 0;
                width: 120%;
                position: relative;
                z-index: 10;
                font-size: 1em;
            }



    /*
    * DataTables framework
    */
    div.dataTables_wrapper {
        background-color: cornflowerblue;
        border: white 1px solid;
    }

    div.dataTables_length {
        float: left;
    }

    div.dataTables_filter {
        float: right;
    }

    div.dataTables_info {
        padding: 9px 6px 6px 6px;
        float: left;
    }

    div.dataTables_paginate {
        float: right;
    }

    div.dataTables_length,
    div.dataTables_filter,
    div.dataTables_paginate {
        padding: 6px;
    }           

    /* Self clearing - http://www.webtoolkit.info/css-clearfix.html */
    .dataTables_wrapper:after {
        content: ".";
        display: block;
        clear: both;
        visibility: hidden;
        line-height: 0;
        height: 0;
    }

    html[xmlns] .dataTables_wrapper {
        display: block;
    }

    * html .dataTables_wrapper {
        height: 1%;
    }

    .knockout {
        background: url(https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRMMuIHp59SNH5qNiwNrF-5dASJ53YPDMucUk3DiMcw4jkbbQcT) -80px -80px;
        color: red;
        -webkit-text-fill-color: transparent;
        -webkit-background-clip: text;
        font-weight: bold;
        font-size: 35px;
        font-family: arial, helvetica;
        width: 100%;
        text-align: center;
    }

    body {
        background: #444;
    }
</style>

@*Aca va el nombre del establecimiento*@
<div class="container-fluid">
    <div class="row" style="color:white">
        <div class="knockout">
            El establecimiento seleccionado es
            @Html.Name((string)ViewBag.establecimiento)
        </div>
    </div>
</div>


<div class="container-fluid" style="margin-top:2%">
    <div class="row slider-text align-items-center">
        <div class="col-lg-offset-4">
            @Html.DropDownList("idSector", (IEnumerable<SelectListItem>)ViewBag.Sectores, "Seleccionar Sector", new { @class = "search_categories", id = "filtro-sector" })
        </div>
        @* Boton de Obtener Semanal *@
        <div class="col-lg-offset-1">

            @Html.ActionLink("Obtener Semanal", "SemanalSector", new { idSector = "1" }, new { @class = "botonNuevo", id = "accionSector" })
        </div>
    </div>
</div>


@*<div class="container-fluid">*@
<div class="row" style="padding:20px; color:white" id="divTablaPV">
    <div class="col-lg-12" style="color:white">
        <table id="example" class="table table-striped table-bordered" style="width:100%; color:black ">
            <thead style="color:black">
                <tr style="background-color:cornflowerblue">
                    <th>Nombre</th>
                    <th>Apellido</th>
                    <th>DNI</th>
                    <th>Especialidad</th>
                    <th>Detalle</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Nombre</td>
                        <td>@item.Apellido</td>
                        <td>@item.DNI</td>
                        <td>@item.Especialidades</td>
                        <td> @Html.ActionLink("Detalle", "DetalleProfesional", "Profesional", new { idProfesional = item.Id }, new { name = "boton" }) </td>

                    </tr>
                }

            </tbody>
        </table>
    </div>
</div>
@*</div>*@

<div>
    <input class="boton" value="Volver" onclick="history.go(-1)" />
</div>

@section Scripts {


    @Scripts.Render("~/plugins/dataTables")

    <script type="text/javascript">




        function FormatoADataTAble() {

            $('#example').DataTable({
                "language": {
                    "lengthMenu": "Muestra _MENU_ profesionales por pagina",
                    "zeroRecords": "No se encontraron profesionales",
                    "info": "Mostrando pagina _PAGE_ de _PAGES_",
                    "infoEmpty": "Sin resultados",
                    "infoFiltered": "(filtrado de _MAX_ profesionales)",
                    "search": "Buscar:",
                    "paginate": {
                        "first": "Primero",
                        "last": "Ultimo",
                        "next": "Siguiente",
                        "previous": "Anterior"
                    },
                }
            });


            document.getElementById('example_wrapper').style.display = 'block';
            document.getElementById('example_length').style.color = 'black';
            document.getElementById('example_info').style.color = 'black';
            document.getElementById('example_filter').style.color = 'black';
            document.getElementById('example_previous').style.background = 'cornflowerblue';
            document.getElementById('example_next').style.background = 'cornflowerblue';


        };




                        function obtenerId() {
                            var nuevoComboBox = document.getElementById("filtro-sector");
                            var indice = nuevoComboBox.options.selectedIndex;
                            var option = nuevoComboBox.options[indice];

                            return option.value.toString();

                        }


    $(document).ready(function () {
            FormatoADataTAble();
            $('#filtro-sector').change(function () {
                var idSectorSel;
                idSectorSel = parseInt(obtenerId());
                if (isNaN(idSectorSel)) {
                    location.reload(true);
                }
                else {
                        var url = "@Url.Action("IndexFiltrado")" + "/?idSector=" + idSectorSel.toString();
                        $.get(url, function (data){
                            $('#divTablaPV').replaceWith(data);
                            FormatoADataTAble();
                            });
                    }
                            });



                            var elementoA = document.getElementById("accionSector");
                            elementoA.onclick = function () {


                                var idSectorSel;
                                idSectorSel = parseInt(obtenerId());

                                if (isNaN(idSectorSel) || (idSectorSel == 0)) {
                                    alert('Recuerde seleccionar el sector primero.');
                                    return false;
                                }

                                var vinculo = elementoA.href;
                                var guillePuto = vinculo.lastIndexOf("=");
                                var nuevoVinculo = vinculo.substring(0, guillePuto);
                                nuevoVinculo += "=";
                                nuevoVinculo += obtenerId();
                                elementoA.href = nuevoVinculo;



                            };





        });

    </script>
}